Adds #324
equalizedigital/accessibility-checker pull request #329
Opened 2023-09-26 22:00 UTC by boonedev

If approved this PR:
- Adds email opt-in panel 
- Fixes misc phpcs issues

2023-09-27 14:39 UTC, SteveJonesDev commented
@boonedev, is the form supposed to disappear after being filled out? Refreshing the page doesn't bring it back either.

2023-09-27 14:44 UTC, SteveJonesDev commented
Looks like it's per user.

2023-09-27 14:48 UTC, boonedev commented
Sounds like a bug. It should:
1) show the form
2) if user email submit is good, the form should thank them, then hide the form and not display again.

Which browser?

2023-09-27 14:51 UTC, boonedev commented
Also, what do you think about pre-populating the form with their email as a convenience?

2023-09-27 14:52 UTC, SteveJonesDev commented
Using the Brave browser.

1. The form is shown
2. I enter an email address
3. It shows a thank you message
4. Then after about a second, the form is dynamically removed from the dom

2023-09-27 14:54 UTC, boonedev commented
So thank-you/hide happens before the submit?

2023-09-27 15:00 UTC, SteveJonesDev commented
Sorry, no I missed a step. I did click the submit button. I don't think the form should be dynamically removed from the page. I'm not sure if you're doing that or Zoho.

2023-09-27 15:14 UTC, boonedev commented
You've got it. Ok to not show the panel on page refresh if they have already signed-up, or should it always show the thank-you message?

2023-09-27 15:33 UTC, SteveJonesDev requested changes
There are two hidden inputs at the bottom of the form that don't have form labels. I can't find them in the PHP so I'm assuming they are being added via JavaScript. I'm not sure if we can fix that or not.
![Screenshot 2023-09-27 at 11 20 47 AM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/a3f806b3-2fbf-49eb-84ef-a2c12bebe48e)

Can we auto-populate the email input with the current logged-in user's email address?
If we do auto-populate we might want to inform screen readers.
Example:
```
<form>
  <label for="username">Username</label>
  <input type="text" id="username" aria-describedby="info-region" />
  <div id="info-region" aria-live="polite" class="info-message"></div>
</form>
```

```
document.addEventListener("DOMContentLoaded", function () {
  const usernameInput = document.getElementById('username');
  const infoRegion = document.getElementById('info-region');
  
  usernameInput.value = 'AutoPopulatedUser';
  infoRegion.textContent = 'Note: Username field has been auto-populated with "' + usernameInput.value + '".';
});
```

2023-09-27 15:33 UTC, SteveJonesDev commented on includes/classes/class-welcome-page.php
> +				<img src="https://zmp-glf.maillist-manage.com/images/spacer.gif" id="refImage" onload="referenceSetter(this)" style="display:none;">
Accessibility: A layout spacer image (which should have null/empty alternative text) does not have an alt attribute.

2023-09-27 15:33 UTC, SteveJonesDev commented on includes/classes/class-welcome-page.php
> +								<label style="font-weight: 600;" for="EMBED_FORM_EMAIL_LABEL">Email Address *</label>
Accessibility: Change asterisk to '(Required)'

2023-09-27 19:23 UTC, boonedev commented
The extra inputs are added by zoho's js onload. I could try to listen for them to exist then replace them with hidden fields if you think it's worth it?

Updates applied:
- no longer removes fields on submit, instead makes the email field readonly and disabled, and disables the submit button
- auto-populates WP email
- adds "Note: The Email Address field has been auto-populated with your WordPress email." notice & removes it when the email field is modified
- adds missing alt for spacer image

2023-09-28 15:42 UTC, SteveJonesDev requested changes
I think the a11y of this is worse. I think removing the form after submission is fine and showing the confirmation message. But we need to ensure the screen reader focuses on that message and reads it out on submit. Let's remove the aria-live message for now.

Here is an example of the confirmation message.
```
<!-- Form HTML -->
<form id="myForm">
  <!-- Form fields go here -->
  <input type="submit" value="Submit" />
</form>

<!-- Confirmation Message -->
<div id="confirmationMessage" tabindex="-1" role="alert" style="outline: none;">
  <!-- This will be populated with the confirmation message on form submit -->
</div>

<script>
// JavaScript to handle form submit
document.getElementById('myForm').addEventListener('submit', function(e){
  e.preventDefault(); // Prevent actual form submit
  
  // Populate the confirmation message
  document.getElementById('confirmationMessage').textContent = 'Your form has been submitted successfully.';
  
  // Set focus to the confirmation message
  document.getElementById('confirmationMessage').focus();
});
</script>
```

2023-09-28 18:43 UTC, boonedev commented
So leave as-is and only remove `aria-describedby` and ` aria-live` attributes below:
```
<input name="CONTACT_EMAIL" id="EMBED_FORM_EMAIL_LABEL" aria-describedby="email-info-region">
<div class="edac-mt-3" id="email-info-region" aria-live="polite" class="info-message"></div>
```
Or re-add removing the form on submit and show a confirm message?

2023-09-28 18:50 UTC, SteveJonesDev commented
This: Or re-add removing the form on submit and show a confirm message?

But only the form, not the whole subscribe container like it did before. Test it with Voice Over and ensure it reads out the confirmation message on submit.

If you need an example install Gravity Forms, create a test form, and set it to submit via Ajax.

2023-09-28 20:23 UTC, boonedev commented
Updated.
- Adds confirmation message with role=alert 
- On submit, removes the form
 - On submit, populates confirmation message text and gives it focus
 - Tested w/Voice Over -on submit confirmation message is read-out

2023-09-28 21:53 UTC, SteveJonesDev requested changes

2023-09-28 21:53 UTC, SteveJonesDev commented on includes/classes/class-welcome-page.php
> +									' . esc_html( __( 'Note: The Email Address field has been auto-populated with your WordPress email.', 'accessibility-checker' ) ) . '
Delete this message.

2023-09-28 21:53 UTC, SteveJonesDev commented on includes/classes/class-welcome-page.php
> +							<div id="confirmationMessage" tabindex="-1" role="alert" style="outline: none;">
The confirmation message is being read out twice by the screen reader. Remove role="alert" and test that it's only being read out once.

2023-09-29 13:15 UTC, boonedev commented
Removed role=alert and confirmed message is announced only once.

2023-09-29 18:41 UTC, SteveJonesDev approved these changes
Please merge.

2023-09-29 18:46 UTC, merged