Hotfix/basic auth fix
equalizedigital/accessibility-checker pull request #457
Opened 2024-01-22 22:24 UTC by boonedev

This PR:
- Removes setting authorization header in rest calls because browser caches that auth and uses for all requests going forward (not just rest).
- Updates composer to pull the most recent version of equalizedigital/accessibility-checker-wp-env.

2024-01-22 22:26 UTC, boonedev commented on includes/enqueue-scripts.php
> -			);
We no longer need to pass auth.

2024-01-22 22:26 UTC, boonedev commented on includes/options-page.php
>  }
Unnecessary.

2024-01-22 22:27 UTC, boonedev commented on src/editorApp/checkPage.js
> -
Removes setting auth headers.

2024-01-22 22:28 UTC, boonedev commented on src/editorApp/checkPage.js
> -
Not used.

2024-01-22 22:28 UTC, boonedev commented on src/editorApp/index.js
> -
Not used.

2024-01-23 03:28 UTC, SteveJonesDev requested changes
It still requires the password with every page load. Here is a screen recording.
https://www.dropbox.com/scl/fi/jmcq29ioanx0zfn73k6zi/video1714334445.mp4?rlkey=3r1el078cy6hsfk2qzjf9mgyu&dl=0

2024-01-23 15:33 UTC, SteveJonesDev approved these changes

2024-01-23 15:33 UTC, merged