Converts purge functions into a class
equalizedigital/accessibility-checker pull request #512
Opened 2024-02-23 22:41 UTC by pattonwebz

Moves the purge methods into a class and sets them as static since they don't require any instantiation or setup.

The only functional change I made was adding a condition to check if the post type exists when operating on CPTs to save needing a query to run if no CPT exists that would match against it.

Closes: #463

2024-02-23 23:00 UTC, pattonwebz commented on admin/class-purge-post-data.php
> + * Uses sql queries to get and purge post data from the database for given post ids or for custom posts by id.
```suggestion
 * Uses sql queries to get and purge post data from the database for given post ids or for custom posts by post_type string.
```

2024-02-23 23:00 UTC, pattonwebz commented on tests/phpunit/PurgePostDataTest.php
> +		$wpdb->insert( // phpcs:ignore WordPress.DB -- this is just one-time use date for testing.
```suggestion
		$wpdb->insert( // phpcs:ignore WordPress.DB -- this is just one-time use data for testing.
```

2024-02-27 22:08 UTC, SteveJonesDev requested changes
@pattonwebz, I added some comments. I think @aristath is going to review this as well, so he might have some feedback too.

2024-02-27 22:08 UTC, SteveJonesDev commented on accessibility-checker.php
> +add_action( 'wp_trash_post', array( Purge_Post_Data::class, 'delete_post' ) );
Move this to the `Admin` class `init()` method so it's only loaded in the admin. https://github.com/pattonwebz/accessibility-checker/blob/william/463/convert-purge-functions-to-class-methods/admin/class-admin.php#L28

2024-02-27 22:08 UTC, SteveJonesDev commented on accessibility-checker.php
> +use EDAC\Admin\Purge_Post_Data;
I noted below to move this to the `Admin` class `init()` method.

2024-02-27 22:08 UTC, SteveJonesDev commented on includes/deprecated/deprecated.php
> + * @deprecated 1.9.0
This milestone is version 2.0.0

2024-02-27 22:08 UTC, SteveJonesDev commented on includes/deprecated/deprecated.php
> + * @deprecated 1.9.0
This milestone is version 2.0.0

2024-02-27 22:08 UTC, SteveJonesDev commented on includes/deprecated/deprecated.php
> + * @deprecated 1.9.0
This milestone is version 2.0.0

2024-02-27 22:08 UTC, SteveJonesDev commented on includes/deprecated/deprecated.php
> +	_deprecated_function( __FUNCTION__, '1.9.0', 'EDAC\Admin\Purge_Post_Data::delete_post' );
2.0.0

2024-02-27 22:08 UTC, SteveJonesDev commented on includes/deprecated/deprecated.php
> +	_deprecated_function( __FUNCTION__, '1.9.0', 'EDAC\Admin\Purge_Post_Data::delete_post_meta' );
2.0.0

2024-02-27 22:08 UTC, SteveJonesDev commented on includes/deprecated/deprecated.php
> +	_deprecated_function( __FUNCTION__, '1.9.0', 'EDAC\Admin\Purge_Post_Data::delete_cpt_posts' );
2.0.0

2024-02-27 22:08 UTC, SteveJonesDev commented on tests/phpunit/PurgePostDataTest.php
> +class PurgePostDataTest extends TestCase {
Why does this extend `TestCase` and not `WP_UnitTestCase` like the other unit tests?

2024-02-27 22:08 UTC, SteveJonesDev commented on tests/phpunit/PurgePostDataTest.php
> +	public function testDeletePostIsCalledOnWpTrashPost() {
I see a test for trash posts but I don't see a test specifically for the `delete_cpt_posts` method. Was that for a reason?

2024-02-27 22:08 UTC, SteveJonesDev commented on admin/class-purge-post-data.php
> +		$site_id    = get_current_blog_id();
I know this is the way it was before but we can avoid these single-use variables in all these methods. We can also improve readability by using multiple lines of code.

Example:
```php
    $wpdb->query( 
        $wpdb->prepare( 
            "DELETE FROM %i WHERE postid = %d AND siteid = %d", 
            $wpdb->prefix . 'accessibility_checker', 
            $post_id, 
            get_current_blog_id() 
        )
    );
```

2024-02-27 22:13 UTC, pattonwebz commented on tests/phpunit/PurgePostDataTest.php
> +class PurgePostDataTest extends TestCase {
I didn't use any methods that don't exist on the base `TestCase` class, which was the only reason. For consistency with other tests, I can swap it to `WP_UnitTestCase` for consistency and refactor it a little.

2024-02-28 02:49 UTC, pattonwebz commented on tests/phpunit/PurgePostDataTest.php
> +	public function testDeletePostIsCalledOnWpTrashPost() {
I added a test for that method, and it also found an issue with the code under test. A mismatch on upper vs lower case table names was causing the data not to get deleted in the custom table.

2024-03-15 19:43 UTC, pattonwebz commented
> @pattonwebz, I'm approving this PR but I did run into a bug while testing, but I don't think it's related. Can you confirm that's the case before merging this PR?
> 
> #535

I was able to reproduce that issue while working on a different branch without these changes so #535 seems unrelated to the changes here and I'll merge this shortly. Posting more details about what I found about that error on the issue thread when I have a minute outline it.

2024-03-15 22:54 UTC, merged