Add a rule and check for empty paragraphs
equalizedigital/accessibility-checker pull request #591
Opened 2024-04-26 14:45 UTC by pattonwebz

This introduces a new rule to the JS scanner that can detect empty paragraph tags (or tags with whitespace inside of them, like spaces or returns).

@amberhinds I am going to need some copy/docs for this scan since it is new and there isn't something existing I can use or point to. An info URL and improved summary to show users in the details view and frontend highlighter. Picking which tags are suitable as well will be needed: https://www.deque.com/axe/core-documentation/api-documentation/#axecore-tags

2024-04-26 14:56 UTC, amberhinds commented
When do you think this rule will be released @pattonwebz?

2024-04-26 14:58 UTC, pattonwebz commented
@amberhinds it can be in the next release (next Tuesday) but if that's too soon we can probably do the week after? I do have one other new rule I will be adding as well that would need docs too.

2024-05-14 04:15 UTC, amberhinds requested changes
@pattonwebz some wording changes.

2024-05-14 04:15 UTC, amberhinds commented on includes/rules.php
> +		'title'     => esc_html__( 'Empty Paragraph Tags', 'accessibility-checker' ),
@pattonwebz please make title singular - "Empty Paragraph Tag" - this will match how we have named other rules.

2024-05-14 04:15 UTC, amberhinds commented on includes/rules.php
> +		'summary'   => esc_html__( 'Paragraph tags that are empty get announced to screen readers with empty content creating unnecessary noise. Paragraphs should never be used for layout purposes.', 'acce
An Empty Paragraph Tag error means there is a paragraph tag present that does not contain content. These are announced by screen readers and create unnecessary noise for blind users. To fix this error, remove the empty paragraphs from the page. If you need to add spacing between sections, this should be done with padding, margins, or a spacer block.

2024-05-15 06:04 UTC, amberhinds commented
Tag: best-practice

This is going to be the documentation link: https://equalizedigital.com/accessibility-checker/empty-paragraph-tag/

I will finish that up in the morning. Let me know if you need anything esle.

2024-05-15 14:29 UTC, amberhinds commented on includes/rules.php
> +		'summary'   => esc_html__( 'An Empty Paragraph Tag error means there is a paragraph tag present that does not contain content. These may be announced by screen readers and create unnecessary noise
This needs to be updated now that it's a warning:

An Empty Paragraph Tag warning means there is a paragraph tag present that does not contain content. These may be announced by screen readers or create confusion for users. To fix this warning, remove the empty paragraphs from the page. If you need to add spacing between sections, this should be done with padding, margins, or a spacer block.

2024-05-15 14:30 UTC, amberhinds commented on includes/rules.php
> +		'slug'      => 'paragraph_should_not_be_empty',
Slug should be empty_paragraph_tag

2024-05-15 14:32 UTC, SteveJonesDev requested changes

2024-05-15 14:32 UTC, SteveJonesDev commented on includes/rules.php
> +		'slug'      => 'paragraph_should_not_be_empty',
Can we change this to `empty_paragraph_tag ` to be consistent with other rule slugs?

2024-05-15 14:32 UTC, SteveJonesDev commented on src/pageScanner/index.js
> +import paragraphShouldNotBeEmpty from './rules/paragraph-should-not-be-empty';
Can we change this to `empty_paragraph_tag`  as well?

2024-05-15 14:32 UTC, SteveJonesDev commented on src/pageScanner/rules/paragraph-should-not-be-empty.js
> +	id: 'paragraph_should_not_be_empty',
Update id `empty_paragraph_tag`.

2024-05-15 14:32 UTC, SteveJonesDev commented on includes/rules.php
> +		'info_url'  => 'https://a11ychecker.com/',
A new URL will be provided.

2024-05-22 18:48 UTC, pattonwebz commented on includes/classes/class-rest-api.php
> +	 *
```suggestion
	 * This can be used to store additional data in the html of the violation.
	 *
	 * @since 1.13.0
```

2024-05-24 14:04 UTC, pattonwebz commented on includes/rules.php
> +		'info_url'  => 'https://equalizedigital.com/accessibility-checker/empty-paragraph-tag/',
```suggestion
		'info_url'  => 'https://a11ychecker.com/help7870',
```

2024-05-24 18:42 UTC, merged