Check possible_heading rule with computedStyles
equalizedigital/accessibility-checker pull request #622
Opened 2024-05-14 21:14 UTC by pattonwebz

This PR moves the possible_heading rule to a JS rule that can check element styling with computedStyles. That prevents any need to parse CSS vars, functions or pseudo-classes since it gets the actual styles the element has after all the cascade is applied.

@amberhinds I will need some help setting the tags that the rule should have.

Sidenote: I like to see PRs that make things more powerful yet are red than green (or orange and blue in my case haha) :) 
![Screenshot from 2024-05-14 22-18-28](https://github.com/equalizedigital/accessibility-checker/assets/3902039/5f085f08-e8a2-4906-adc5-3ddc3ed51f0a)

Fixes: #612

2024-05-14 22:09 UTC, amberhinds commented
@pattonwebz what do you mean by tags?

2024-05-14 22:20 UTC, pattonwebz commented
@amberhinds sorry I should have linked to the list. I need to know the correct tags and a category from the list here: https://www.deque.com/axe/core-documentation/api-documentation/#axecore-tags

I presume this is the list but let me know if it misses anything or something shuoldn't be in the list:

wcag2a
wcag2aa
wcag21a
wcag21aa
wcag22aa
wcag131  
wcag241
wcag246

2024-05-15 04:47 UTC, amberhinds commented
Got it. Here are the tags:

- wcag2a
- wcag131
- wcag241

2024-05-15 05:02 UTC, amberhinds commented
@pattonwebz did you use this? https://dequeuniversity.com/rules/axe/4.9/p-as-heading?application=RuleDescription

2024-05-15 13:57 UTC, pattonwebz commented
> @pattonwebz did you use this? [dequeuniversity.com/rules/axe/4.9/p-as-heading?application=RuleDescription](https://dequeuniversity.com/rules/axe/4.9/p-as-heading?application=RuleDescription)

I didn't use that rule because it doesn't work as well as what we did in PHP. I replicated our own rule instead of using this. 

The rule from axe-core doesn't check as many things as we do (it doesn't care about font size), and in my testing, the things it found were marked as `incomplete`, which means it needs additional review to determine a pass or fail. It can't tell anything with certainty from the data I have run it against — probably why it's still flagged as an experimental rule.

![Screenshot from 2024-05-15 14-56-09](https://github.com/equalizedigital/accessibility-checker/assets/3902039/336261b9-ab67-44f9-a534-8bbdb4ad0e1b)

Our rule catches 8 items, and the axe-core rule catches 0 and returns a 'can't tell' result with only one item from my test data.

2024-05-15 15:43 UTC, amberhinds commented
Thanks for that info! Sounds like our rule is better. I wonder if we need to document anywhere when our rule is better than an axe rule so we remember that for the future.

2024-05-15 16:04 UTC, pattonwebz commented
I can add some comments in the code for this rule so that we can remember the next time we touch the code. I'll see if I can find a place to document it outside of the code for ourselves to and form the basis of some copy for the plugin docs that explains why our check does certain things that axe-core misses.

2024-05-15 16:34 UTC, amberhinds commented
Code comments sound good. Outside the code tracking here makes sense: https://docs.google.com/spreadsheets/d/10vbbz4Y4uit76z73U8ffa9h6NN_ha5TC6Vfkt2-4IxI/edit?usp=sharing

2024-05-23 02:20 UTC, SteveJonesDev requested changes

2024-05-23 02:20 UTC, SteveJonesDev commented on src/pageScanner/helpers/helpers.js
> +	if ( node === null || node === 'undefined' || node.nodeType !== Node.ELEMENT_NODE ) {
While your code is more readable to me, would it be an improvement to use `! node` as it would cover both `null` and `undefined` falsy values?
```suggestion
if ( ! node || node.nodeType !== Node.ELEMENT_NODE )  {
```

2024-05-23 02:20 UTC, SteveJonesDev commented on src/pageScanner/helpers/helpers.js
> +	return parseFloat( window.getComputedStyle( node ).fontSize );
If this was to fail in getting the font size would a fallback be a good idea or would a failure result in a `0` value anyway?

```suggestion
	const fontSize = window.getComputedStyle( node ).fontSize;
	return parseFloat( fontSize ) || 0;
```

2024-05-23 02:20 UTC, SteveJonesDev commented on src/pageScanner/checks/paragraph-styled-as-header.js
> +		const pixelSize = fontSizeInPx( node );
I'm not sure what happens before this but is there any value in returning early here if node is empty?

```js
if ( ! node ) {
     return false;
}
```

2024-05-23 02:20 UTC, SteveJonesDev commented on src/pageScanner/checks/paragraph-styled-as-header.js
> +		// long paragraphs or with size under 16px are unlikely to be headers.
```suggestion
		// Long paragraphs or those with font size under 16px are unlikely to be headers.
```

2024-05-23 02:20 UTC, SteveJonesDev commented on src/pageScanner/checks/paragraph-styled-as-header.js
> +		// paragraphs that are 20px or more are probably headers.
```suggestion
		// Paragraphs that are 20px or more are probably headers.
```

2024-05-23 02:20 UTC, SteveJonesDev commented on src/pageScanner/checks/paragraph-styled-as-header.js
> +		// didn't find anything indicating this is a possible header.
```suggestion
		// Didn't find anything indicating this is a possible header.
```

2024-05-23 02:20 UTC, SteveJonesDev commented on src/pageScanner/rules/possible-heading.js
> +		'cat.text',
Does this still need the actual tags?

2024-05-24 18:45 UTC, pattonwebz commented on src/pageScanner/helpers/helpers.js
> +	return parseFloat( window.getComputedStyle( node ).fontSize );
A failure could result in `NaN` so it will be good to add some catch here.

2024-05-24 18:57 UTC, merged