Show a notice when fixes settings are saved on options page
equalizedigital/accessibility-checker pull request #817
Opened 2024-11-19 00:10 UTC by pattonwebz

When fixes settings are saved, a transient is set to be used as a flag for notifications. It is used in the fixes_page.php partial to output a notice about rescanning and flushing the cache.

It's done this way rather than via admin_notifications because we are unhooking all other notifications when on the settings pages.

![Screenshot from 2024-11-18 21-49-25](https://github.com/user-attachments/assets/cf6f62ea-bbb0-4007-a014-e770b0afe3cc)

## Checklist

- [x] PR is linked to the main issue in the repo
- [ ] Tests are added that cover changes

2024-11-19 17:08 UTC, SteveJonesDev requested changes

2024-11-19 17:08 UTC, SteveJonesDev commented on partials/admin-page/fixes-page.php
> +			<p><?php esc_html_e( 'Settings saved. You need to rescan your site for the updates to be confirmed and reflected in site stats. If you have a caching plugin on your site make sure to flush is so t
```suggestion
			<p><?php esc_html_e( 'Settings Saved. To confirm and reflect these updates in your site's statistics, please rescan your site. If you are using a caching plugin, make sure to clear the cache to ensure the updated fixes are applied correctly.', 'accessibility-checker' ); ?></p>
```

2024-11-19 18:32 UTC, pattonwebz commented on partials/admin-page/fixes-page.php
> +			<p><?php esc_html_e( 'Settings Saved. To confirm and reflect these updates in your site's statistics, please rescan your site. If you are using a caching plugin, make sure to clear the cache to en
```suggestion
			<p><?php esc_html_e( "Settings Saved. To confirm and reflect these updates in your site's statistics, please rescan your site. If you are using a caching plugin, make sure to clear the cache to ensure the updated fixes are applied correctly.", 'accessibility-checker' ); ?></p>
```

2024-11-22 17:38 UTC, SteveJonesDev approved these changes

2024-11-22 18:32 UTC, merged